[package]
name = "hw08-chaotic_tumbling"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
csv = "1"
plotters = { version = "0.3", features = ["bitmap_backend", "svg_backend"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
